import React from "react";

const Dashboard = () => {
  return (
    <div className=" text-white p-6">
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
      <div>sadkflkfasdklsa</div>
    </div>
  );
};

export default Dashboard;
